'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Menu, X } from 'lucide-react'

const projects = [
  { id: '01', short: 'ZENITH', title: 'Zenith Satellite System', subtitle: 'Satellite-based hazard detection & environmental monitoring', tech: ['ESP32-CAM', 'LoRa', 'Environmental Sensors', 'Image Processing'], description: 'Developed a system to identify hazards and monitor environmental conditions in remote areas, including fires, chemical spills, temperature, humidity, and gas levels.', kind: 'zenith' },
  { id: '02', short: 'FOOD DELIVERY', title: 'Online Food Delivery Web Application', subtitle: 'Full-stack web application', tech: ['Java', 'JDBC', 'Servlets', 'JSP', 'MySQL'], description: 'Developed a full-stack web application using MVC architecture and DAO pattern with login, menu, cart, checkout, sessions, and transaction handling.', kind: 'food' },
  { id: '03', short: 'NOTICE BOARD', title: 'Wireless Display Notice Board', subtitle: 'Bluetooth-based embedded system', tech: ['Arduino', 'Bluetooth'], description: 'Designed a system for remote message display using Bluetooth communication, embedded systems, circuit design, and hardware interfacing.', kind: 'notice' },
]
const builds = [
  { title: 'TrainWake', subtitle: 'Smart Train Journey Alarm', kind: 'train', detail: 'BENGALURU → DESTINATION' },
  { title: 'Wishly', subtitle: 'Wishlist & Memory Organizer', kind: 'wish', detail: 'TRAVEL · FOOD · EXPERIENCES' },
  { title: 'Smart Task Scheduler', subtitle: 'Full-Stack Task Management Application', kind: 'task', detail: 'MON · TUE · WED · THU · FRI' },
]
const experiences = [
  { id: '01', duration: '1 MONTH', company: 'Syscon Instruments Pvt Ltd', role: 'Intern', flow: 'STRAIN GAUGE → SIGNAL CONDITIONING → ADC → SENSOR → DATA', text: 'Worked on strain-gauge-based sensor systems for force measurement, including signal conditioning, ADC conversion, sensor interfacing, calibration, testing, data acquisition, PCB, wiring, soldering, instrumentation, quality testing, and documentation.' },
  { id: '02', duration: '1 MONTH', company: 'Teknic Euchner', role: 'Trainee', flow: 'SENSOR → CALIBRATION → PRE-TESTING → VERIFICATION', text: 'Performed calibration, pre-testing, and testing of proximity sensors. Tested specified sensing distances such as 1 mm and 1.75 mm and verified sensor performance and sensing accuracy.' },
  { id: '03', duration: 'INTERNSHIP', company: 'Extion Infotech', role: 'Intern, Remote Certification Program', flow: 'FRONTEND → BACKEND → DATABASE → SCHEDULER', text: 'Completed project-based training in full-stack development fundamentals and developed a Smart Task Scheduler with task creation, recurring schedules, reminders, calendar view, and completion tracking.' },
]
const skillGroups = { SOFTWARE: ['Java', 'Core Java', 'OOP', 'JDBC', 'Servlets', 'J2EE Basics', 'DAO', 'MVC', 'MySQL', 'DBMS', 'SQL', 'HTML', 'CSS', 'JavaScript', 'React'], 'ELECTRONICS & VLSI': ['CMOS Basics', 'NMOS', 'PMOS', 'Analog Circuits', 'Current Mirror', 'Differential Pair', 'Op-Amp Basics', 'Physical Design Flow', 'Setup/Hold/Slack', 'Signal Conditioning', 'Sensors', 'PCB Basics', 'Soldering', 'Embedded Systems'], TOOLS: ['MATLAB', 'Multisim', 'Arduino IDE', 'VS Code', 'Eclipse', 'MySQL Workbench', 'Apache Tomcat'] }

function Label({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p> }
function External({ children, href = '#' }: { children: React.ReactNode; href?: string }) { return <a className="external" href={href}>{children}<ArrowUpRight aria-hidden="true" /></a> }
function SectionTitle({ label, title, eyebrow }: { label: string; title: string; eyebrow?: string }) { return <div className="section-title"><Label>{label}</Label>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div> }
function SystemVisual() { return <div className="system-visual"><div className="visual-grid" /><div className="scan-line" /><div className="system-orbit orbit-a" /><div className="system-orbit orbit-b" /><div className="system-panel"><div className="panel-top"><span>SYSTEM STATUS</span><span>PB / 001</span></div>{['VLSI', 'EMBEDDED', 'SOFTWARE', 'RESEARCH'].map(item => <div className="status-row" key={item}><span>{item}</span><b>ACTIVE <i /></b></div>)}<div className="metrics"><strong>08<small>+</small></strong><strong>03<small>EXP</small></strong><strong>01<small>IEEE</small></strong></div></div><span className="coordinates">12° 58&apos; 16&quot; N<br />77° 35&apos; 42&quot; E</span><span className="scroll-note">SCROLL TO EXPLORE ↓</span></div> }
function ProjectVisual({ kind }: { kind: string }) { return <div className={`project-visual ${kind}`}><div className="visual-frame"><span className="visual-caption">SYSTEM / {kind.toUpperCase()}</span>{kind === 'zenith' && <><div className="radar" /><div className="signal-line" /><span className="sensor-values">TEMP 28°C<br />HUM 64%<br />GAS 0.4</span><span className="hazard-box">HAZARD<br />DETECTED</span><div className="flow-stack"><span>ESP32-CAM</span><i>↓</i><span>IMAGE PROCESSING</span><i>↓</i><span>LoRa</span></div></>}{kind === 'food' && <><div className="food-window"><span>MENU / CART / CHECKOUT</span><b>ORDER_DATABASE</b><i>LOGIN　●●●　PAYMENT</i></div><div className="food-dots">01 02 03 04</div></>}{kind === 'notice' && <><div className="bt-device">ARDUINO</div><div className="bt-wave">)))</div><div className="bt-screen">DISPLAY<br />NOTICE</div></>}</div></div> }
function ProductVisual({ kind, detail }: { kind: string; detail: string }) { return <div className={`product-visual ${kind}`}><span className="visual-caption">PRODUCT / LIVE CONCEPT</span>{kind === 'train' && <><b>TRAIN JOURNEY</b><strong>{detail}</strong><div className="route-line">●━━━━━━━◉</div><small>ETA　12 MIN　　ALARM　<span>ON</span></small></>}{kind === 'wish' && <><b>MY WISHES</b><strong>{detail}</strong><div className="wish-list">TRAVEL　✓<br />FOOD　　＋<br />MEMORIES　＋</div></>}{kind === 'task' && <><b>WEEK / TASKS</b><strong>{detail}</strong><div className="calendar-bars"><i /><i /><i /><i /><i /></div></>}</div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selected, setSelected] = useState(projects[0])
  const [activeSkill, setActiveSkill] = useState('Java')
  return <main>
    <header className="site-header wrapper"><a href="#top" className="wordmark">PB.</a><nav className={menuOpen ? 'nav-open' : ''}>{['about', 'dna', 'work', 'experience', 'skills', 'research', 'contact'].map(item => <a href={`#${item}`} key={item} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav><External href="https://www.linkedin.com">LINKEDIN</External><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="top" className="hero wrapper"><div className="hero-copy"><Label>PERSONAL PORTFOLIO<br />ECE · VLSI · SOFTWARE</Label><h1>PRAGATHI<span>.</span><small>B</small></h1><p className="hero-kicker">I BUILD ACROSS<br /><strong>HARDWARE <i>×</i> SOFTWARE</strong></p><p className="hero-description">Electronics and Communication Engineering graduate building across VLSI, physical design, embedded systems, Java and full-stack development.</p><div className="hero-actions"><a className="button button-dark" href="#work">VIEW MY WORK <ArrowDown /></a><a className="button button-outline" href="https://www.linkedin.com">CONNECT ON LINKEDIN <ArrowUpRight /></a></div><External href="https://github.com">GITHUB</External></div><SystemVisual /></section>
    <section id="about" className="section wrapper about-section"><SectionTitle label="01 / ABOUT" title="ECE ENGINEER\nBUILDING ACROSS\nHARDWARE + SOFTWARE" eyebrow="WHO I AM" /><div className="about-content"><p className="large-copy">I&apos;m an Electronics and Communication Engineering graduate with hands-on exposure to VLSI, physical design, analog and digital electronics, sensors, signal conditioning, PCB implementation, Java, databases and full-stack development.</p><div className="about-blocks"><div><b>HARDWARE</b><span>VLSI · SENSORS · PCB · EMBEDDED</span></div><div><b>SOFTWARE</b><span>JAVA · SQL · DBMS · FULL STACK</span></div><div><b>RESEARCH</b><span>IEEE · ESP32-CAM · LoRa</span></div></div><div className="data-flow"><span>HARDWARE</span><i>→</i><span>DATA</span><i>→</i><span>SOFTWARE</span></div></div></section>
    <section id="dna" className="section wrapper dna-section"><SectionTitle label="02 / ENGINEERING DNA" title="HOW I WORK" /><div className="dna-grid">{[['IDEA', 'Problem solving'], ['DESIGN', 'Circuits · Architecture'], ['BUILD', 'Hardware · Software'], ['TEST', 'Calibration · Debugging'], ['ITERATE', 'Improve · Refine']].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><b>{title}</b><p>{text}</p><i className="dna-signal" /></article>)}</div></section>
    <section id="build" className="section wrapper build-section"><SectionTitle label="03 / WHAT I BUILD" title="WHAT I WORK ACROSS" /><div className="build-grid"><article className="build-side hardware"><span className="side-number">01</span><h3>HARDWARE</h3><div className="build-list">VLSI · CMOS · Analog Electronics · Digital Electronics · Sensors · PCB · Embedded Systems</div><div className="trace-lines" /></article><div className="build-bridge">HARDWARE <i>→</i> SOFTWARE</div><article className="build-side software"><span className="side-number">02</span><h3>SOFTWARE</h3><div className="build-list">Java · Full Stack · SQL · DBMS · React · Web Development</div><div className="code-lines">01 const build = practical;<br />02 connect(hardware, software);</div></article></div></section>
    <section id="work" className="section wrapper work-section"><SectionTitle label="04 / SELECTED WORK" title="SELECTED PROJECTS" /><div className="project-layout"><aside className="project-nav">{projects.map(project => <button className={selected.id === project.id ? 'active' : ''} onClick={() => setSelected(project)} key={project.id}><span>{project.id}</span>{project.short}</button>)}</aside><article className="case-study"><div className="case-copy"><span className="project-number">{selected.id} / COLLEGE PROJECT</span><h3>{selected.title}</h3><p className="project-subtitle">{selected.subtitle}</p><div className="tech-chips">{selected.tech.map(item => <span key={item}>{item}</span>)}</div><p className="body-copy">{selected.description}</p><button className="project-link" onClick={() => setSelected(selected)}>VIEW CASE STUDY <ArrowUpRight /></button></div><ProjectVisual kind={selected.kind} /></article></div></section>
    <section className="section wrapper personal-section"><SectionTitle label="05 / PERSONAL BUILDS" title="BUILDING OUTSIDE THE CLASSROOM" /><div className="product-grid">{builds.map(build => <article className="product-card" key={build.title}><div className="product-meta"><span>PERSONAL BUILD</span><h3>{build.title}</h3><p>{build.subtitle}</p></div><ProductVisual kind={build.kind} detail={build.detail} /></article>)}</div></section>
    <section id="experience" className="section wrapper experience-section"><SectionTitle label="06 / EXPERIENCE" title="REAL SYSTEMS" /><div className="timeline">{experiences.map(item => <article className="timeline-row" key={item.id}><div className="timeline-marker">{item.id}</div><div className="timeline-meta"><span>{item.duration}</span><h3>{item.company}</h3><p>{item.role}</p></div><div><p className="body-copy">{item.text}</p><div className="flow-line">{item.flow}</div></div></article>)}</div></section>
    <section id="skills" className="section wrapper skills-section"><SectionTitle label="07 / SKILLS" title="INTERACTIVE SKILL NETWORK" /><div className="skill-network"><div className="skill-core"><button className={activeSkill === 'Java' ? 'active' : ''} onClick={() => setActiveSkill('Java')}>JAVA</button><button className={activeSkill === 'CMOS' ? 'active' : ''} onClick={() => setActiveSkill('CMOS')}>CMOS</button><button className={activeSkill === 'SENSORS' ? 'active' : ''} onClick={() => setActiveSkill('SENSORS')}>SENSORS</button></div><div className="skill-branches"><h3>{activeSkill}</h3><p>{activeSkill === 'Java' ? 'OOP → JDBC → SERVLETS → DAO → MVC' : activeSkill === 'CMOS' ? 'NMOS → PMOS → DIGITAL LOGIC → PHYSICAL DESIGN' : 'SIGNAL CONDITIONING → CALIBRATION → PCB → EMBEDDED'}</p></div></div><div className="skill-columns">{Object.entries(skillGroups).map(([group, items]) => <div key={group}><b>{group}</b><p>{items.map(item => <span key={item}>{item}</span>)}</p></div>)}</div></section>
    <section id="research" className="section wrapper research-section"><SectionTitle label="08 / RESEARCH" title="IEEE RESEARCH" /><div className="research-grid"><div><h3>Satellite-based Image Transmission with Hazard Detection and Real-Time Environmental Monitoring using LoRa and ESP32-CAM</h3><span className="eyebrow">IEEE · ICSSS 2025</span><External>VIEW RESEARCH</External></div><div className="research-visual"><div className="earth-grid" /><div className="orbit research-orbit" /><div className="research-flow">ESP32-CAM<br />↓<br />IMAGE<br />↓<br />HAZARD<br />↓<br />LoRa<br />↓<br />GROUND STATION</div></div></div><div className="stats">{[['250+', 'PROGRAMMING PROBLEMS'], ['03', 'TECHNICAL EXPERIENCES'], ['01', 'IEEE RESEARCH PAPER'], ['08+', 'PROJECTS & BUILDS']].map(([n, l]) => <div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
    <section className="section wrapper current-section"><SectionTitle label="09 / CURRENTLY BUILDING" title="CURRENT FOCUS" /><div className="current-grid">{[['TRAINWAKE', 'BUILDING', '80%'], ['WISHLY', 'EXPLORING', '60%'], ['VLSI / PHYSICAL DESIGN', 'LEARNING', '50%']].map(([title, status, width]) => <article key={title}><span>STATUS: {status}</span><h3>{title}</h3><i><b style={{ width }} /></i><small>VISUAL PROGRESS INDICATOR</small></article>)}</div></section>
    <section className="section wrapper beyond-section"><SectionTitle label="10 / BEYOND THE RESUME" title="WHAT KEEPS ME CURIOUS" /><div className="beyond-grid">{[['BUILD', 'Things I create'], ['LEARN', 'Things I’m exploring'], ['EXPLORE', 'Things that inspire my ideas']].map(([title, text]) => <article key={title}><span>{title}</span><p>{text}</p><ArrowUpRight /></article>)}</div></section>
    <section className="section wrapper education-section"><SectionTitle label="11 / EDUCATION" title="THE FOUNDATION" /><div className="education-copy"><span>B.E.</span><h3>Electronics and Communication Engineering</h3><p>CMR Institute of Technology</p><strong>CGPA 8.2 · 2025</strong><div className="education-line">2021 <i /> 2025</div></div></section>
    <section id="contact" className="contact-section wrapper"><Label>12 / CONTACT</Label><h2>LET&apos;S BUILD<br /><em>SOMETHING REAL.</em></h2><div className="contact-links"><External href="mailto:pragatireddy900@gmail.com"><span>EMAIL<small>pragatireddy900@gmail.com</small></span></External><External href="https://www.linkedin.com"><span>LINKEDIN<small>LinkedIn</small></span></External><External href="https://github.com"><span>GITHUB<small>GitHub</small></span></External></div></section>
    <footer className="site-footer wrapper"><span>Pragathi B.</span><span>ECE · VLSI · SOFTWARE</span><span>© 2026</span></footer>
  </main>
}
