'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Menu, X } from 'lucide-react'

const projects = [
  { number: '01', title: 'Zenith Satellite System', subtitle: 'Satellite-based hazard detection & environmental monitoring', tech: 'ESP32-CAM · Environmental Sensors · Arduino IDE · Dipole Transmitter', points: ['Detects hazards in remote areas', 'Monitors temperature, humidity and gas levels', 'Captures and transmits images using ESP32-CAM'], kind: 'signal' },
  { number: '02', title: 'Online Food Delivery Web Application', subtitle: 'Full-stack web application', tech: 'Java · JDBC · Servlets · JSP · MySQL · HTML · CSS', points: ['Supports login, menu, cart and checkout', 'Uses MVC architecture with DAO pattern', 'Handles sessions and transaction processing'], kind: 'database' },
  { number: '03', title: 'Wireless Display Notice Board', subtitle: 'Bluetooth-based embedded system', tech: 'Arduino · Bluetooth', points: ['Displays messages remotely through Bluetooth', 'Uses Arduino for embedded system control', 'Enables wireless communication and message updates'], kind: 'bluetooth' },
]

const builds = [
  { number: '01', title: 'TrainWake', subtitle: 'Smart Train Journey Alarm', points: ['Set journey and destination', 'Track journey using location services', 'Trigger alerts near destination', 'Customize alarm timings'], visual: 'route' },
  { number: '02', title: 'Wishly', subtitle: 'Wishlist & Memory Organizer', points: ['Create and organize personal wishes', 'Save places, food and experiences', 'Mark completed wishes', 'Add photos and memories'], visual: 'memory' },
  { number: '03', title: 'VLSI / Physical Design', subtitle: 'Learning & Practice', points: ['Physical design fundamentals', 'Timing and layout concepts', 'Building practical depth'], visual: 'memory' },
]

const experiences = [
  { number: '01', duration: '1 MONTH', company: 'Syscon Instruments Pvt Ltd', role: 'Intern', description: 'Worked on strain-gauge-based sensor systems for force measurement, including signal conditioning, ADC conversion, sensor interfacing, calibration, testing, data acquisition, PCB, wiring, soldering, instrumentation, quality testing, and documentation.', tags: ['STRAIN GAUGE', 'SIGNAL CONDITIONING', 'ADC', 'SENSORS', 'PCB', 'CALIBRATION'] },
  { number: '02', duration: '1 MONTH', company: 'Teknic Euchner', role: 'Trainee', description: 'Performed calibration, pre-testing, and testing of proximity sensors. Tested specified sensing distances such as 1 mm and 1.75 mm and verified sensor performance and sensing accuracy.', tags: ['PROXIMITY SENSORS', 'CALIBRATION', 'PRE-TESTING', 'SENSOR TESTING'] },
  { number: '03', duration: 'INTERNSHIP', company: 'Extion Infotech', role: 'Intern, Remote Certification Program', description: 'Completed project-based training in full-stack development fundamentals and developed a Smart Task Scheduler with task creation, recurring schedules, reminders, calendar view, and completion tracking.', tags: ['JAVA', 'FULL STACK', 'DATABASE', 'WEB DEVELOPMENT'] },
]

const skills = {
  SOFTWARE: ['Java', 'Core Java', 'OOP', 'JDBC', 'Servlets', 'J2EE Basics', 'DAO', 'MVC', 'MySQL', 'DBMS', 'SQL', 'HTML', 'CSS', 'JavaScript', 'React'],
  'ELECTRONICS & VLSI': ['CMOS Basics', 'NMOS', 'PMOS', 'Analog Circuits', 'Current Mirror', 'Differential Pair', 'Op-Amp Basics', 'Physical Design Flow', 'Setup/Hold/Slack', 'Signal Conditioning', 'Sensors', 'PCB Basics', 'Soldering', 'Embedded Systems'],
  TOOLS: ['MATLAB', 'Multisim', 'Arduino IDE', 'VS Code', 'Eclipse', 'MySQL Workbench', 'Apache Tomcat'],
}

function Label({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p> }
function External({ children, href = '#' }: { children: React.ReactNode; href?: string }) { return <a className="external" href={href}>{children}<ArrowUpRight aria-hidden="true" /></a> }
function SectionHead({ label, children }: { label: string; children: React.ReactNode }) { return <div className="section-head"><Label>{label}</Label><h2>{children}</h2></div> }

function SystemVisual() {
  return <div className="system-visual" aria-label="Engineering system status visualization">
    <div className="visual-grid" /><div className="scan-line" /><div className="orbit orbit-one" /><div className="orbit orbit-two" />
    <span className="node node-one" /><span className="node node-two" /><span className="node node-three" />
    <div className="system-panel"><div className="panel-top"><span>SYSTEM STATUS</span><span>PB / 001</span></div><div className="status-list"><div><span>VLSI</span><b>ACTIVE <i /></b></div><div><span>EMBEDDED</span><b>ACTIVE <i /></b></div><div><span>SOFTWARE</span><b>ACTIVE <i /></b></div><div><span>RESEARCH</span><b>ACTIVE <i /></b></div></div><div className="metrics"><strong>08<small>+</small></strong><strong>03<small>EXP</small></strong><strong>01<small>IEEE</small></strong></div></div>
    <span className="coordinates">12° 58&apos; 16&quot; N<br />77° 35&apos; 42&quot; E</span><span className="scroll-note">SCROLL TO EXPLORE ↓</span>
  </div>
}

function ProjectVisual({ kind }: { kind: string }) {
  return <div className={`project-visual ${kind}`} aria-hidden="true"><div className="visual-frame"><span className="visual-caption">SYSTEM / {kind.toUpperCase()}</span>{kind === 'signal' && <><div className="radar" /><div className="signal-path"><i /><i /><i /><i /></div><span className="sensor-readout">TEMP 28°C<br />HUM 64%<br />GAS 0.04</span><span className="hazard">HAZARD<br />DETECTED</span></>}{kind === 'database' && <><div className="browser-line" /><div className="browser-window"><span>MENU / CART / CHECKOUT</span><b>ORDER_DATABASE</b><em>01 02 03 04</em></div><div className="db-node">MYSQL</div></>}{kind === 'bluetooth' && <><div className="bt-ring" /><div className="bt-line" /><div className="bt-device">ARDUINO</div><div className="bt-screen">DISPLAY<br />NOTICE</div></>}</div></div>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedProject, setSelectedProject] = useState<(typeof projects)[number] | null>(null)
  const [activeSkill, setActiveSkill] = useState('Java')
  return <main>
    <header className="site-header wrapper"><a href="#top" className="wordmark">PB.</a><nav className={menuOpen ? 'nav-open' : ''} aria-label="Main navigation"><a href="#about" onClick={() => setMenuOpen(false)}>ABOUT</a><a href="#work" onClick={() => setMenuOpen(false)}>WORK</a><a href="#experience" onClick={() => setMenuOpen(false)}>EXPERIENCE</a><a href="#research" onClick={() => setMenuOpen(false)}>RESEARCH</a><a href="#contact" onClick={() => setMenuOpen(false)}>CONTACT</a></nav><External href="https://www.linkedin.com">LINKEDIN</External><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></header>

    <section id="top" className="hero wrapper"><div className="hero-copy"><Label>PERSONAL PORTFOLIO<br />ECE · VLSI · SOFTWARE</Label><h1>PRAGATHI<br /><span>B.</span></h1><p className="hero-kicker">I BUILD ACROSS<br /><strong>HARDWARE <i>×</i> SOFTWARE</strong></p><p className="hero-description">Electronics and Communication Engineering graduate building across VLSI, physical design, embedded systems, Java and full-stack development.</p><div className="hero-actions"><a className="button button-dark" href="#work">VIEW MY WORK <ArrowDown /></a><a className="button button-outline" href="https://www.linkedin.com">CONNECT ON LINKEDIN <ArrowUpRight /></a></div><External href="https://github.com">GITHUB</External></div><SystemVisual /></section>

    <section id="about" className="section wrapper about-section"><p className="section-label">01 / ABOUT</p><div className="about-intro"><div className="about-identity"><span className="about-kicker">WHO I AM</span><h2>ECE ENGINEER<br />BUILDING ACROSS<br /><span className="about-heading-accent">HARDWARE<br />AND SOFTWARE.</span></h2><div className="engineering-profile" aria-label="Engineering profile connecting VLSI, sensors, data and software"><span className="profile-title">ENGINEERING PROFILE</span><div className="profile-line profile-line-vlsi"><span>VLSI</span><i /><b /></div><div className="profile-line profile-line-sensors"><span>SENSORS</span><i /><b /></div><div className="profile-line profile-line-data"><span>DATA</span><i /></div><div className="profile-software"><span>SOFTWARE</span><small>JAVA · SQL · FULL STACK</small></div></div><span className="profile-foot">HARDWARE → SIGNAL → DATA → SOFTWARE → SYSTEM</span><span className="build-label">BUILDING ACROSS SYSTEMS</span></div><div className="about-content"><span className="about-kicker">INTRODUCTION</span><p className="large-copy">I&apos;m an Electronics and Communication Engineering graduate with hands-on exposure to VLSI, physical design, analog and digital electronics, sensors, signal conditioning, PCB implementation, Java, databases and full-stack development.</p><p className="body-copy">I enjoy turning technical concepts into practical systems — from sensor-based hardware to software applications.</p><div className="indicators"><div><span>HARDWARE</span><b>VLSI · SENSORS · PCB · EMBEDDED</b></div><div><span>SOFTWARE</span><b>JAVA · SQL · DBMS · FULL STACK</b></div><div><span>RESEARCH</span><b>IEEE · ESP32-CAM · LoRa</b></div></div><div className="how-i-work"><span className="how-title">HOW I WORK</span><div className="work-sequence"><div><b>01</b><strong>LEARN</strong><p>Understand fundamentals.</p></div><i /><div><b>02</b><strong>BUILD</strong><p>Turn concepts into systems.</p></div><i /><div><b>03</b><strong>TEST</strong><p>Measure, debug, refine.</p></div><i /><div><b>04</b><strong>CONNECT</strong><p>Bring hardware and software together.</p></div></div></div></div></div><div className="about-flow" aria-label="Hardware to software system flow"><span>HARDWARE</span><i /> <span>SENSORS</span><i /> <span>DATA</span><i /> <span>SOFTWARE</span><i /> <span>SYSTEM</span></div></section>

    <section id="stack" className="section wrapper stack-section"><div className="stack-heading"><Label>05 / SKILLS</Label><h2>HARDWARE <span className="stack-heading-accent">×</span> SOFTWARE</h2></div><div className="stack-map"><article className="stack-group hardware-stack"><span className="stack-index">01</span><h3>HARDWARE &amp; VLSI</h3><div className="skill-tags">{['CMOS', 'NMOS & PMOS', 'Analog & Digital Electronics', 'VLSI Physical Design', 'Timing Concepts', 'Signal Conditioning', 'Sensors & Interfacing', 'PCB Basics'].map((skill) => <span key={skill}>{skill}</span>)}</div></article><span className="stack-node node-one" aria-hidden="true" /><article className="stack-group software-stack"><span className="stack-index">02</span><h3>SOFTWARE</h3><div className="skill-tags">{['Java', 'OOP', 'JDBC', 'Servlets', 'SQL & DBMS', 'HTML & CSS', 'JavaScript', 'React'].map((skill) => <span key={skill}>{skill}</span>)}</div></article><span className="stack-node node-two" aria-hidden="true" /><article className="stack-group tools-stack"><span className="stack-index">03</span><h3>TOOLS</h3><div className="skill-tags">{['MATLAB', 'Multisim', 'Arduino IDE', 'VS Code', 'Eclipse', 'MySQL Workbench'].map((skill) => <span key={skill}>{skill}</span>)}</div></article></div></section>

    <section id="work" className="section wrapper work-section"><SectionHead label="03 / SELECTED WORK">TECHNOLOGY MADE<br /><span className="heading-accent">TANGIBLE.</span></SectionHead><div className="project-showcase">{projects.map((project) => <article className="showcase-project" key={project.number}><div className="project-copy"><span className="project-number">{project.number} / COLLEGE PROJECT</span><h3>{project.title}</h3><p className="project-subtitle">{project.subtitle}</p><p className="tech-line">{project.tech}</p><ul className="project-points">{project.points.map((point) => <li key={point}>{point}</li>)}</ul><button className="project-link" type="button" onClick={() => setSelectedProject(project)}>VIEW PROJECT <ArrowUpRight aria-hidden="true" /></button></div><ProjectVisual kind={project.kind} /></article>)}</div></section>

    <section className="section wrapper personal-section"><SectionHead label="04 / PERSONAL BUILDS">ALWAYS BUILDING<br /><span className="heading-accent">SOMETHING.</span></SectionHead><div className="build-showcase">{builds.map((build) => <article className="personal-panel" key={build.title}><div><span className="project-number">{build.number}</span><h3>{build.title}</h3><p className="project-subtitle">{build.subtitle}</p><ul>{build.points.map((point) => <li key={point}>{point}</li>)}</ul></div><div className={`mini-visual ${build.visual}`} aria-hidden="true"><span>{build.visual === 'route' ? 'TRAIN / ROUTE' : build.visual === 'memory' ? 'WISHLY / MEMORY' : 'TASKS / CALENDAR'}</span><b>{build.visual === 'route' ? '●━━━━━━◉' : build.visual === 'memory' ? '01 / 24  02 / 24' : '09:00  TASK  12:30'}</b></div></article>)}</div></section>

    <section id="experience" className="section wrapper experience-section"><SectionHead label="04 / EXPERIENCE">LEARNING THROUGH<br /><span className="heading-accent">REAL SYSTEMS.</span></SectionHead><div className="timeline">{experiences.map((experience) => <article className="timeline-row" key={experience.number}><div className="timeline-marker"><span>{experience.number}</span></div><div className="timeline-meta"><span>{experience.duration}</span><h3>{experience.company}</h3><p>{experience.role}</p></div><div><p className="body-copy">{experience.description}</p><div className="experience-tags">{experience.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>

    

    <section id="research" className="section wrapper research-section"><SectionHead label="05 / RESEARCH">FROM CAMERA TO<br /><span className="heading-accent">SATELLITE.</span></SectionHead><div className="research-grid"><div><span className="eyebrow">IEEE RESEARCH PAPER · ICSSS 2025 · IEEE PUBLISHER</span><h3>Satellite-based Image Transmission with Hazard Detection and Real-Time Environmental Monitoring using LoRa and ESP32-CAM</h3><External>VIEW RESEARCH</External></div><div className="research-visual"><div className="earth-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="satellite">ESP32-CAM</span><span className="research-dot">HAZARD</span></div></div><div className="stats"><div><strong>250<small>+</small></strong><span>PROGRAMMING PROBLEMS</span></div><div><strong>03</strong><span>TECHNICAL EXPERIENCES</span></div><div><strong>01</strong><span>IEEE RESEARCH PAPER</span></div><div><strong>08<small>+</small></strong><span>PROJECTS &amp; BUILDS</span></div></div></section>

    <section className="section wrapper current-section" hidden><SectionHead label="06 / CURRENTLY BUILDING">ALWAYS<br />BUILDING SOMETHING.</SectionHead><div className="current-grid">{[['TRAINWAKE','Smart Train Journey Alarm','BUILDING'],['WISHLY','Wishlist & Memory Organizer','EXPLORING'],['VLSI / PHYSICAL DESIGN','Learning & Practice','LEARNING']].map(([title, subtitle, status]) => <article key={title}><span>STATUS: {status}</span><h3>{title}</h3><p>{subtitle}</p><i><b style={{ width: status === 'BUILDING' ? '72%' : status === 'EXPLORING' ? '48%' : '34%' }} /></i></article>)}</div></section>

    <section className="section wrapper education-section"><SectionHead label="07 / EDUCATION">THE FOUNDATION.</SectionHead><div className="education-copy"><span>BACHELOR OF ENGINEERING</span><h3>Electronics and Communication Engineering</h3><p>CMR Institute of Technology</p><strong>CGPA: 8.2 <i>·</i> 2025</strong></div></section>

    <section id="contact" className="contact-section wrapper"><Label>08 / CONTACT</Label><h2>HAVE AN IDEA?<br />LET&apos;S BUILD<br /><em>SOMETHING PRACTICAL.</em></h2><div className="contact-links"><External href="mailto:pragatireddy900@gmail.com"><span>EMAIL<small>pragatireddy900@gmail.com</small></span></External><External href="https://www.linkedin.com"><span>LINKEDIN<small>LinkedIn</small></span></External><External href="https://github.com"><span>GITHUB<small>GitHub</small></span></External></div></section>
    <footer className="site-footer wrapper"><span>Pragathi B.</span><span>ECE · VLSI · SOFTWARE</span><span>© 2026</span></footer><p className="footer-note">BUILT WITH CURIOSITY.</p>
    {selectedProject && <div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><div className="modal-inner"><button className="modal-close" type="button" onClick={() => setSelectedProject(null)}>CLOSE ×</button><span className="project-number">{selectedProject.number} / PROJECT DETAIL</span><h2 id="project-modal-title">{selectedProject.title}</h2><p className="project-subtitle">{selectedProject.subtitle}</p><div className="modal-grid"><ProjectVisual kind={selectedProject.kind} /><div><span className="eyebrow">OVERVIEW</span><p className="body-copy">{selectedProject.description}</p><span className="eyebrow">TECHNOLOGY</span><p className="tech-line">{selectedProject.tech}</p><span className="eyebrow">SYSTEM FLOW</span><p className="body-copy">Input → processing → validation → practical output.</p></div></div></div></div>}
  </main>
}
