'use client'

import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, Menu, X } from 'lucide-react'
import './zenith.css'
import { ZenithCaseStudy } from './zenith-case-study'

const projects = [
  { number: '01', title: 'Zenith Satellite System', subtitle: 'Satellite-based hazard detection & environmental monitoring', tech: 'ESP32-CAM · Environmental Sensors · Arduino IDE · Dipole Transmitter', points: ['Detects hazards in remote areas', 'Monitors temperature, humidity and gas levels', 'Captures and transmits images using ESP32-CAM'], kind: 'signal' },
  { number: '02', title: 'Online Food Delivery Web Application', subtitle: 'Full-stack web application', tech: 'Java · JDBC · Servlets · JSP · MySQL · HTML · CSS', points: ['Supports login, menu, cart and checkout', 'Uses MVC architecture with DAO pattern', 'Handles sessions and transaction processing'], kind: 'database' },
  { number: '03', title: 'Wireless Display Notice Board', subtitle: 'Bluetooth-based embedded system', tech: 'Arduino · Bluetooth', points: ['Displays messages remotely through Bluetooth', 'Uses Arduino for embedded system control', 'Enables wireless communication and message updates'], kind: 'bluetooth' },
]

const builds = [
  { number: '01', title: 'TrainWake', subtitle: 'Smart Train Journey Alarm', points: ['Set journey and destination', 'Track journey using location services', 'Trigger alerts near destination', 'Customize alarm timings'], visual: 'route' },
  { number: '02', title: 'Wishly', subtitle: 'Wishlist & Memory Organizer', points: ['Create and organize personal wishes', 'Save places, food and experiences', 'Mark completed wishes', 'Add photos and memories'], visual: 'memory' },
  { number: '03', title: 'Smart Task Scheduler', subtitle: 'Full-Stack Task Management', points: ['Create tasks with deadlines and priorities', 'Manage recurring tasks and schedules', 'Track tasks through a calendar', 'Send reminders and notifications'], visual: 'tasks' },
]

const experiences = [
  { number: '01', duration: '1 MONTH', company: 'Syscon Instruments Pvt Ltd', role: 'Intern', description: 'Worked on strain-gauge-based sensor systems for force measurement, including signal conditioning, ADC conversion, sensor interfacing, calibration, testing, data acquisition, PCB, wiring, soldering, instrumentation, quality testing, and documentation.', tags: ['STRAIN GAUGE', 'SIGNAL CONDITIONING', 'ADC', 'SENSORS', 'PCB', 'CALIBRATION'] },
  { number: '02', duration: '1 MONTH', company: 'Teknic Euchner', role: 'Trainee', description: 'Performed calibration, pre-testing, and testing of proximity sensors. Tested specified sensing distances such as 1 mm and 1.75 mm and verified sensor performance and sensing accuracy.', tags: ['PROXIMITY SENSORS', 'CALIBRATION', 'PRE-TESTING', 'SENSOR TESTING'] },
  { number: '03', duration: 'INTERNSHIP', company: 'Extion Infotech', role: 'Intern, Remote Certification Program', description: 'Completed project-based training in full-stack development fundamentals and developed a Smart Task Scheduler with task creation, recurring schedules, reminders, calendar view, and completion tracking.', tags: ['JAVA', 'FULL STACK', 'DATABASE', 'WEB DEVELOPMENT'] },
]

const skills = {
  SOFTWARE: ['Java', 'Core Java', 'OOP', 'JDBC', 'Servlets', 'J2EE Basics', 'DAO', 'MVC', 'MySQL', 'DBMS', 'SQL', 'HTML', 'CSS', 'JavaScript', 'React'],
  'ELECTRONICS & VLSI': ['CMOS Basics', 'NMOS', 'PMOS', 'Analog Circuits', 'Current Mirror', 'Differential Pair', 'Op-Amp Basics', 'Physical Design Flow', 'Setup/Hold/Slack', 'Signal Conditioning', 'Sensors', 'PCB Basics', 'Soldering', 'Embedded Systems'],
  TOOLS: ['MATLAB', 'Multisim', 'Arduino IDE', 'VS Code', 'Eclipse', 'MySQL Workbench', 'Apache Tomcat'],
}

function Label({ children }: { children: React.ReactNode }) { return <p className="section-label">{children}</p> }
function External({ children, href = '#' }: { children: React.ReactNode; href?: string }) { return <a className="external" href={href}>{children}<ArrowUpRight aria-hidden="true" /></a> }
function SectionHead({ label, children }: { label: string; children: React.ReactNode }) { return <div className="section-head"><Label>{label}</Label><h2>{children}</h2></div> }

function SystemVisual() {
  return <div className="system-visual" aria-label="Engineering system status visualization">
    <div className="visual-grid" /><div className="scan-line" /><div className="orbit orbit-one" /><div className="orbit orbit-two" />
    <span className="node node-one" /><span className="node node-two" /><span className="node node-three" />
    <div className="system-panel"><div className="panel-top"><span>SYSTEM STATUS</span><span>PB / 001</span></div><div className="status-list"><div><span>VLSI</span><b>ACTIVE <i /></b></div><div><span>EMBEDDED</span><b>ACTIVE <i /></b></div><div><span>SOFTWARE</span><b>ACTIVE <i /></b></div><div><span>RESEARCH</span><b>ACTIVE <i /></b></div></div><div className="metrics"><strong>08<small>+</small></strong><strong>03<small>EXP</small></strong><strong>01<small>IEEE</small></strong></div></div>
    <span className="coordinates">12° 58&apos; 16&quot; N<br />77° 35&apos; 42&quot; E</span><span className="scroll-note">SCROLL TO EXPLORE ↓</span>
  </div>
}

const zenithImages = {
  hardwareOne: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-z1rCKU5B3x1ilLzyVQqTNWwKxxX98G.png',
  hardwareTwo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-cPdIrIAmo3NDbLsT64iiVYCb1c3KZO.png',
  fieldTest: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lTbEsf2wylsgL7CTcYET8kQManBd4v.png',
  sensorGui: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-xXrLv81gnr8LmIIpgpYVHxOggUnjEZ.png',
  hazardAnalysis: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-BqrJF8Z3lssrxc0SDQZsp220e3z5tt.png',
  systemOverview: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-eiBPRdospfj4qoSDeVzdeFy3RYGSxb.png',
  groundStation: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-tatxiT4g0Cbv2TW8bsyj7pCeGTBdyP.png',
} as const

function ZenithImage({ src, alt, caption, onOpen }: { src: string; alt: string; caption: string; onOpen: (src: string, alt: string) => void }) {
  return <figure className="zenith-image"><button type="button" onClick={() => onOpen(src, alt)}><img src={src} alt={alt} /></button><figcaption><span>{caption}</span><b>OPEN IMAGE ↗</b></figcaption></figure>
}

function ZenithCaseStudyLegacy({ onClose }: { onClose: () => void }) {
  const [lightbox, setLightbox] = useState<{ src: string; alt: string } | null>(null)
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') lightbox ? setLightbox(null) : onClose() }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', onKey); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKey) } }, [lightbox, onClose])
  const openImage = (src: string, alt: string) => setLightbox({ src, alt })
  return <div className="zenith-overlay" role="dialog" aria-modal="true" aria-label="Zenith Satellite System project detail"><div className="zenith-shell"><header className="zenith-header"><span className="project-number">01 / PROJECT DETAIL</span><button className="zenith-close" type="button" onClick={onClose}>CLOSE ×</button></header><div className="zenith-hero"><div><span className="eyebrow">SATELLITE-BASED HAZARD DETECTION</span><h2>Zenith Satellite<br /><em>System</em></h2></div><div><p className="zenith-subtitle">SATELLITE-BASED HAZARD DETECTION &amp; ENVIRONMENTAL MONITORING</p><p className="zenith-tech">ESP32-CAM · ENVIRONMENTAL SENSORS · ARDUINO IDE · DIPOLE TRANSMITTER</p><p className="zenith-intro">Developed a system to identify hazards and monitor environmental conditions in remote areas, including fires, chemical spills, temperature, humidity, and gas levels.</p></div></div>

<section className="zenith-section"><span className="eyebrow">01 / SYSTEM OVERVIEW</span><h3>From remote sensing to ground-station analysis.</h3><div className="zenith-image-grid"><ZenithImage src={zenithImages.hardwareOne} alt="Zenith remote node prototype with ESP32-CAM, sensors and LoRa module" caption="REMOTE NODE / SATELLITE PROTOTYPE" onOpen={openImage} /><ZenithImage src={zenithImages.hardwareTwo} alt="Zenith remote node LoRa hardware prototype" caption="REMOTE NODE / LoRa HARDWARE" onOpen={openImage} /></div><div className="zenith-flow">{['REMOTE NODE','IMAGE + SENSOR DATA','LoRa E32','GROUND STATION','IMAGE PROCESSING','HAZARD DETECTION'].map((item) => <span key={item}>{item}</span>)}</div></section>

<section className="zenith-section zenith-two-col"><div><span className="eyebrow">02 / HOW THE SYSTEM WORKS</span><h3>Remote Node</h3><ul className="zenith-list"><li>ESP32-CAM → captures images</li><li>ESP32 → handles telemetry + LoRa transmission</li><li>Sensors → BMP280 and MPU6050</li><li>Encoding → Base64 for LoRa packet transfer</li><li>Power → Li-Po battery with buck converter</li></ul></div><ZenithImage src={zenithImages.systemOverview} alt="Zenith system overview flowchart" caption="SYSTEM OVERVIEW / COMMAND AND DATA PATH" onOpen={openImage} /></section>

<section className="zenith-section zenith-two-col"><ZenithImage src={zenithImages.groundStation} alt="Zenith ground station system flowchart" caption="GROUND STATION / DATA PROCESSING FLOW" onOpen={openImage} /><div><span className="eyebrow">03 / GROUND STATION</span><h3>Ground Station</h3><ul className="zenith-list"><li>Receives LoRa packets via E32 module</li><li>Decodes sensor + image data in real time</li><li>Python GUI → displays telemetry</li><li>Image Processing → reassembles and displays images</li><li>Hazard Mapping → thresholding + Voronoi safe path overlay</li></ul></div></section>

<section className="zenith-section"><span className="eyebrow">04 / SENSOR DATA &amp; GUI</span><h3>Sensor Data &amp; Visualization</h3><div className="zenith-image-grid zenith-sensor-grid"><ZenithImage src={zenithImages.fieldTest} alt="Received field-test image of a colorful cube-like calibration object" caption="FIELD TEST IMAGE / QVGA 320×240" onOpen={openImage} /><ZenithImage src={zenithImages.sensorGui} alt="Raw sensor telemetry beside a ground-station GUI visualization" caption="SENSOR DATA / RAW TELEMETRY + GUI" onOpen={openImage} /></div><div className="zenith-note-grid"><div><strong>FIELD TEST IMAGE</strong><p>Received image from field test (QVGA 320×240)</p></div><div><strong>GROUND STATION GUI</strong><p>Raw sensor data rendered alongside the live visualization.</p></div></div></section>

<section className="zenith-section"><span className="eyebrow">05 / IMAGE TRANSMISSION</span><h3>Image Transmission</h3><div className="zenith-terminal"><span>REAL-TIME IMAGE DECODING</span><p>Terminal displaying real-time image decoding logs.</p><code>ESP32-CAM :: CAPTURE COMPLETE<br />BASE64 PACKET :: ENCODED<br />LoRa E32 :: TRANSMISSION READY<br />GROUND STATION :: RECONSTRUCTION</code></div><div className="zenith-flow">{['ESP32-CAM','IMAGE CAPTURE','BASE64 ENCODING','LoRa TRANSMISSION','GROUND STATION','IMAGE RECONSTRUCTION'].map((item) => <span key={item}>{item}</span>)}</div></section>

<section className="zenith-section"><span className="eyebrow">06 / HAZARD DETECTION</span><h3>Hazard Detection &amp; Safe Path Analysis</h3><ZenithImage src={zenithImages.hazardAnalysis} alt="Four-stage hazard analysis showing raw image, hazard map, Voronoi analysis and safe paths" caption="01 RAW IMAGE · 02 HAZARD MAP · 03 VORONOI ANALYSIS · 04 SAFE PATH" onOpen={openImage} /><p className="zenith-intro">Image processing identifies hazard regions through thresholding and derives traversable paths using Voronoi-based analysis.</p></section>

<section className="zenith-section"><span className="eyebrow">07 / COMPLETE SYSTEM FLOW</span><h3>Complete System Flow</h3><div className="zenith-flow zenith-flow-long">{['CAPTURE','SENSE','ENCODE','TRANSMIT','DECODE','PROCESS','DETECT','VISUALIZE'].map((item) => <span key={item}>{item}</span>)}</div><div className="zenith-info-grid">{[['HARDWARE','ESP32-CAM · ESP32 · BMP280 · MPU6050 · LoRa E32'],['COMMUNICATION','LoRa wireless transmission'],['PROCESSING','Python · OpenCV · Image Processing'],['OUTPUT','Environmental Monitoring · Image Transmission · Hazard Detection']].map(([title, text]) => <div key={title}><strong>{title}</strong><p>{text}</p></div>)}</div></section>

<section className="zenith-takeaway"><span className="eyebrow">08 / PROJECT TAKEAWAY</span><h3>Connecting remote sensing,<br />wireless transmission,<br /><em>and intelligent image analysis.</em></h3><p>College Project · Zenith Satellite System</p></section></div>{lightbox && <div className="zenith-lightbox" role="dialog" aria-modal="true"><button type="button" onClick={() => setLightbox(null)}>CLOSE ×</button><img src={lightbox.src} alt={lightbox.alt} /></div>}</div>
}

const trainWakeImages = [
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20215643-QWMR1fCyr769sdLge0LGYAKARrv2HZ.png', alt: 'TrainWake home screen with train journey alarm dashboard', title: 'APP HOME', description: 'Set your journey and destination.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20215653-EBUalannigDDduFyiv6igEpRziC8cx.png', alt: 'TrainWake set journey screen with source, destination and alert settings', title: 'JOURNEY SETUP', description: 'Choose source, destination, train and alert settings.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20215701-Zjq8qwgmrJ9ibUWdQNeumQTmqiu1y2.png', alt: 'TrainWake live tracking screen showing route and distance to Mysore', title: 'LIVE TRACKING', description: 'Track the train and distance to your destination.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20215708-mlm2TYuxotQ3MuLJ4flWGpMSkRJ23D.png', alt: 'TrainWake destination alert notification near Mysore Junction', title: 'DESTINATION ALERT', description: 'Receive an alert when you are near your destination.' },
] as const

function TrainWakeGallery({ onClose }: { onClose: () => void }) {
  const [index, setIndex] = useState(0)
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') setIndex((current) => (current + trainWakeImages.length - 1) % trainWakeImages.length); if (event.key === 'ArrowRight') setIndex((current) => (current + 1) % trainWakeImages.length) }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', onKey); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKey) } }, [onClose])
  const image = trainWakeImages[index]
  return <div className="trainwake-modal-backdrop" role="dialog" aria-modal="true" aria-label="TrainWake image gallery"><div className="trainwake-modal"><header><div><span className="project-number">TRAINWAKE</span><h2>SMART TRAIN JOURNEY ALARM</h2></div><span className="trainwake-count">{String(index + 1).padStart(2, '0')} / 04</span></header><button className="trainwake-modal-close" type="button" onClick={onClose}>CLOSE ×</button><figure><div className="trainwake-image-wrap"><img src={image.src} alt={image.alt} /></div><figcaption><strong>{String(index + 1).padStart(2, '0')} — {image.title}</strong><p>{image.description}</p></figcaption></figure><footer><button type="button" onClick={() => setIndex((current) => (current + trainWakeImages.length - 1) % trainWakeImages.length)}>PREVIOUS</button><div className="trainwake-dots" aria-label="Gallery slides">{trainWakeImages.map((item, itemIndex) => <button key={item.title} type="button" className={itemIndex === index ? 'active' : ''} aria-label={`Show ${item.title}`} onClick={() => setIndex(itemIndex)} />)}</div><button type="button" onClick={() => setIndex((current) => (current + 1) % trainWakeImages.length)}>NEXT</button></footer></div></div>
}

const wishlyImages = [
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20220640-YW4rajeCHkOlwSNHzkWiKgqm2dIPru.png', alt: 'Wishly home dashboard with Food, Travel, Shopping, Movies and Shows, Experiences, and Others categories', title: 'HOME', description: 'Organize wishes across the categories that matter to you.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20220651-c67jQJ5wPhPIznP96EHhjViYv1aK20.png', alt: 'Wishly food discovery screen with saved areas and restaurants', title: 'FOOD', description: 'Discover and save restaurants, cafés, and places by area.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20220710-kKNx6DNwFdci1UVcnq7O9rD8IW9Ndm.png', alt: 'Wishly saved Third Wave Coffee place detail screen with rating and notes', title: 'PLACE DETAILS', description: 'Keep ratings, notes, photos, and wishlist status together.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20220726-m5D4b08xMmCf2zUUZVTH7Gc5lkZfbx.png', alt: 'Wishly travel map with saved destinations and places', title: 'TRAVEL MAP', description: 'See saved places and travel destinations on one map.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20220734-mTHkPatVUGC3FdMYFPCfz5srHExtlb.png', alt: 'Wishly progress screen showing wishlist category completion', title: 'PROGRESS', description: 'Track completed wishes and see progress across categories.' },
] as const

function WishlyGallery({ onClose }: { onClose: () => void }) {
  const [index, setIndex] = useState(0)
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') setIndex((current) => (current + wishlyImages.length - 1) % wishlyImages.length); if (event.key === 'ArrowRight') setIndex((current) => (current + 1) % wishlyImages.length) }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', onKey); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKey) } }, [onClose])
  const image = wishlyImages[index]
  return <div className="trainwake-modal-backdrop wishly-modal-backdrop" role="dialog" aria-modal="true" aria-label="Wishly image gallery"><div className="trainwake-modal wishly-modal"><header><div><span className="project-number">WISHLY</span><h2>WISHLIST &amp; MEMORY ORGANIZER</h2></div><span className="trainwake-count">{String(index + 1).padStart(2, '0')} / 05</span></header><button className="trainwake-modal-close" type="button" onClick={onClose}>CLOSE ×</button><figure><div className="trainwake-image-wrap wishly-image-wrap"><img src={image.src} alt={image.alt} /></div><figcaption><strong>{String(index + 1).padStart(2, '0')} / {image.title}</strong><p>{image.description}</p></figcaption></figure><footer><button type="button" onClick={() => setIndex((current) => (current + wishlyImages.length - 1) % wishlyImages.length)}>PREVIOUS ←</button><div className="trainwake-dots" aria-label="Wishly gallery slides">{wishlyImages.map((item, itemIndex) => <button key={item.title} type="button" className={itemIndex === index ? 'active' : ''} aria-label={`Show ${item.title}`} onClick={() => setIndex(itemIndex)} />)}</div><button type="button" onClick={() => setIndex((current) => (current + 1) % wishlyImages.length)}>NEXT →</button></footer></div></div>
}

const schedulerSlides = [
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20222825-mqoxNaUbB3PMN4zePlaZGTRTqtjTCc.png', title: 'DASHBOARD', description: 'Overview of daily tasks, priorities, progress and upcoming deadlines.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20222844-STDFNxbfwSThUCS9VaPbbznvXeL82c.png', title: 'CREATE TASK', description: 'Create tasks with deadlines, priorities, categories, recurring schedules and reminders.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20222856-exRrtKMhZee86fihTssnnQFXXqv7Uj.png', title: 'CALENDAR', description: 'Calendar view for planning and tracking scheduled tasks.' },
  { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-30%20222913-FA0mRiqx33nuE5OCMoL9dCFVIiwQY0.png', title: 'REMINDERS & COMPLETED TASKS', description: 'Track reminders, upcoming tasks and completed activities in one place.' },
] as const

function SchedulerGallery({ onClose }: { onClose: () => void }) {
  const [index, setIndex] = useState(0)
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') setIndex((current) => (current + schedulerSlides.length - 1) % schedulerSlides.length); if (event.key === 'ArrowRight') setIndex((current) => (current + 1) % schedulerSlides.length) }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', onKey); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', onKey) } }, [onClose])
  const slide = schedulerSlides[index]
  return <div className="trainwake-modal-backdrop scheduler-modal-backdrop" role="dialog" aria-modal="true" aria-label="Smart Task Scheduler image gallery" onClick={onClose}><div className="trainwake-modal scheduler-modal" onClick={(event) => event.stopPropagation()}><header><div><span className="project-number">SMART TASK SCHEDULER / SNEAK PEEK</span><h2>Built around everyday productivity.</h2></div><span className="trainwake-count">{String(index + 1).padStart(2, '0')} / 04</span></header><button className="trainwake-modal-close" type="button" onClick={onClose}>CLOSE ×</button><figure><div className="trainwake-image-wrap scheduler-image-wrap"><img src={slide.src} alt={`Smart Task Scheduler ${slide.title.toLowerCase()} screen overview`} /></div><figcaption><strong>{String(index + 1).padStart(2, '0')} / {slide.title}</strong><p>{slide.description}</p></figcaption></figure><footer><button type="button" disabled={index === 0} onClick={() => setIndex((current) => (current + schedulerSlides.length - 1) % schedulerSlides.length)}>← PREVIOUS</button><div className="trainwake-dots" aria-label="Smart Task Scheduler gallery slides">{schedulerSlides.map((item, itemIndex) => <button key={item.title} type="button" className={itemIndex === index ? 'active' : ''} aria-label={`Show ${item.title}`} onClick={() => setIndex(itemIndex)} />)}</div><button type="button" disabled={index === schedulerSlides.length - 1} onClick={() => setIndex((current) => (current + 1) % schedulerSlides.length)}>NEXT →</button></footer></div></div>
}

function ProjectVisual({ kind }: { kind: string }) {
  return <div className={`project-visual ${kind}`} aria-hidden="true"><div className="visual-frame"><span className="visual-caption">SYSTEM / {kind.toUpperCase()}</span>{kind === 'signal' && <><div className="radar" /><div className="signal-path"><i /><i /><i /><i /></div><span className="sensor-readout">TEMP 28°C<br />HUM 64%<br />GAS 0.04</span><span className="hazard">HAZARD<br />DETECTED</span></>}{kind === 'database' && <><div className="database-placeholder"><span>ORDER FLOW</span><b>MENU → CART → CHECKOUT</b></div></>}{kind === 'bluetooth' && <><div className="bt-ring" /><div className="bt-line" /><div className="bt-device">ARDUINO</div><div className="bt-screen">DISPLAY<br />NOTICE</div></>}</div></div>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedProject, setSelectedProject] = useState<(typeof projects)[number] | null>(null)
  const [activeSkill, setActiveSkill] = useState('Java')
  const [trainWakeOpen, setTrainWakeOpen] = useState(false)
  const [wishlyOpen, setWishlyOpen] = useState(false)
  const [schedulerOpen, setSchedulerOpen] = useState(false)
  return <main>
    <header className="site-header wrapper"><a href="#top" className="wordmark">PB.</a><nav className={menuOpen ? 'nav-open' : ''} aria-label="Main navigation"><a href="#about" onClick={() => setMenuOpen(false)}>ABOUT</a><a href="#work" onClick={() => setMenuOpen(false)}>WORK</a><a href="#experience" onClick={() => setMenuOpen(false)}>EXPERIENCE</a><a href="#research" onClick={() => setMenuOpen(false)}>RESEARCH</a><a href="#contact" onClick={() => setMenuOpen(false)}>CONTACT</a></nav><External href="https://www.linkedin.com">LINKEDIN</External><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></header>

    <section id="top" className="hero wrapper"><div className="hero-copy"><Label>PERSONAL PORTFOLIO<br />ECE · VLSI · SOFTWARE</Label><h1>PRAGATHI<br /><span>B.</span></h1><p className="hero-kicker">I BUILD ACROSS<br /><strong>HARDWARE <i>×</i> SOFTWARE</strong></p><p className="hero-description">Electronics and Communication Engineering graduate building across VLSI, physical design, embedded systems, Java and full-stack development.</p><div className="hero-actions"><a className="button button-dark" href="#work">VIEW MY WORK <ArrowDown /></a><a className="button button-outline" href="https://www.linkedin.com">CONNECT ON LINKEDIN <ArrowUpRight /></a></div><External href="https://github.com">GITHUB</External></div><SystemVisual /></section>

    <section id="about" className="section wrapper about-section"><p className="section-label">01 / ABOUT</p><div className="about-intro"><div className="about-identity"><span className="about-kicker">WHO I AM</span><h2>ECE ENGINEER<br />BUILDING ACROSS<br /><span className="about-heading-accent">HARDWARE<br />AND SOFTWARE.</span></h2><div className="engineering-profile" aria-label="Engineering profile connecting VLSI, sensors, data and software"><span className="profile-title">ENGINEERING PROFILE</span><div className="profile-line profile-line-vlsi"><span>VLSI</span><i /><b /></div><div className="profile-line profile-line-sensors"><span>SENSORS</span><i /><b /></div><div className="profile-line profile-line-data"><span>DATA</span><i /></div><div className="profile-software"><span>SOFTWARE</span><small>JAVA · SQL · FULL STACK</small></div></div><span className="build-label">BUILDING ACROSS SYSTEMS</span></div><div className="about-content"><span className="about-kicker">INTRODUCTION</span><p className="large-copy">I&apos;m an Electronics and Communication Engineering graduate with hands-on exposure to VLSI, physical design, analog and digital electronics, sensors, signal conditioning, PCB implementation, Java, databases and full-stack development.</p><p className="body-copy about-body-copy">I enjoy turning technical concepts into practical systems — from sensor-based hardware to software applications.</p><div className="indicators"><div><span>HARDWARE</span><b>VLSI · SENSORS · PCB · EMBEDDED</b></div><div><span>SOFTWARE</span><b>JAVA · SQL · DBMS · FULL STACK</b></div><div><span>RESEARCH</span><b>IEEE · ESP32-CAM · LoRa</b></div></div><div className="how-i-work"><span className="how-title">HOW I WORK</span><div className="work-sequence"><div><b>01</b><strong>LEARN</strong><p>Understand fundamentals.</p></div><i /><div><b>02</b><strong>BUILD</strong><p>Turn concepts into systems.</p></div><i /><div><b>03</b><strong>TEST</strong><p>Measure, debug, refine.</p></div><i /><div><b>04</b><strong>CONNECT</strong><p>Bring hardware and software together.</p></div></div></div></div></div><div className="about-flow" aria-label="Hardware to software system flow"><span>HARDWARE</span><i /> <span>SENSORS</span><i /> <span>DATA</span><i /> <span>SOFTWARE</span><i /> <span>SYSTEM</span></div></section>

    <section id="stack" className="section wrapper stack-section"><div className="stack-heading"><Label>05 / SKILLS</Label><h2>HARDWARE <span className="stack-heading-accent">×</span> SOFTWARE</h2></div><div className="stack-map"><article className="stack-group hardware-stack"><span className="stack-index">01</span><h3>HARDWARE &amp; VLSI</h3><div className="skill-tags">{['CMOS', 'NMOS & PMOS', 'Analog & Digital Electronics', 'VLSI Physical Design', 'Timing Concepts', 'Signal Conditioning', 'Sensors & Interfacing', 'PCB Basics'].map((skill) => <span key={skill}>{skill}</span>)}</div></article><span className="stack-node node-one" aria-hidden="true" /><article className="stack-group software-stack"><span className="stack-index">02</span><h3>SOFTWARE</h3><div className="skill-tags">{['Java', 'OOP', 'JDBC', 'Servlets', 'SQL & DBMS', 'HTML & CSS', 'JavaScript', 'React'].map((skill) => <span key={skill}>{skill}</span>)}</div></article><span className="stack-node node-two" aria-hidden="true" /><article className="stack-group tools-stack"><span className="stack-index">03</span><h3>TOOLS</h3><div className="skill-tags">{['MATLAB', 'Multisim', 'Arduino IDE', 'VS Code', 'Eclipse', 'MySQL Workbench'].map((skill) => <span key={skill}>{skill}</span>)}</div></article></div></section>

    <section id="work" className="section wrapper work-section"><SectionHead label="03 / SELECTED WORK">TECHNOLOGY MADE<br /><span className="heading-accent">TANGIBLE.</span></SectionHead><div className="project-showcase">{projects.map((project) => <article className="showcase-project" key={project.number}><div className="project-copy"><span className="project-number">{project.number} / COLLEGE PROJECT</span><h3>{project.title}</h3><p className="project-subtitle">{project.subtitle}</p><p className="tech-line">{project.tech}</p><ul className="project-points">{project.points.map((point) => <li key={point}>{point}</li>)}</ul><button className="project-link" type="button" onClick={() => setSelectedProject(project)}>VIEW PROJECT <ArrowUpRight aria-hidden="true" /></button></div><ProjectVisual kind={project.kind} /></article>)}</div></section>

    <section className="section wrapper personal-section"><SectionHead label="04 / PERSONAL BUILDS">THINGS I<br />BUILD FOR<br /><span className="heading-accent">EVERYDAY LIFE.</span></SectionHead><div className="build-showcase">{builds.map((build) => <article className="personal-panel" key={build.title}><div><span className="project-number">{build.number}</span><h3>{build.title}</h3><p className="project-subtitle">{build.subtitle}</p><ul>{build.points.map((point) => <li key={point}>{point}</li>)}</ul></div><div className={`mini-visual ${build.visual}`}><span>{build.visual === 'route' ? 'TRAVEL UTILITY' : build.visual === 'memory' ? 'PERSONAL ORGANIZER' : 'FULL-STACK APPLICATION'}{<button className={build.visual === 'route' ? 'trainwake-sneak-peek' : build.visual === 'memory' ? 'wishly-sneak-peek trainwake-sneak-peek' : 'scheduler-sneak-peek trainwake-sneak-peek'} type="button" onClick={() => build.visual === 'route' ? setTrainWakeOpen(true) : build.visual === 'memory' ? setWishlyOpen(true) : setSchedulerOpen(true)}>SNEAK PEEK ↗</button>}</span>{build.visual === 'route' ? <b>TRAIN / ROUTE<br />●━━━━━━━●━━━━━━◎</b> : build.visual === 'memory' ? <b>WISHES<br />01 PLACES<br />02 FOOD<br />03 EXPERIENCES<br />04 MEMORIES</b> : <b>MON&nbsp;&nbsp;TUE&nbsp;&nbsp;WED&nbsp;&nbsp;THU<br />09:00&nbsp;&nbsp;TASK<br />12:30&nbsp;&nbsp;MEETING<br />18:00&nbsp;&nbsp;REMINDER</b>}</div></article>)}</div></section>

    <section id="experience" className="section wrapper experience-section"><div className="experience-heading"><Label>04 / EXPERIENCE</Label><div><h2>FROM SIGNALS<br /><span className="heading-accent">TO SYSTEMS.</span></h2><p>Three experiences. One growing technical direction.</p></div></div><div className="experience-progression" aria-hidden="true"><div><span>01</span><i /><span>02</span><i /><span>03</span></div><div><b>SENSOR</b><b>CALIBRATE</b><b>BUILD</b></div></div><div className="experience-stations">{experiences.map((experience, index) => <article className={`experience-station station-${index + 1}`} key={experience.number}><div className="station-copy"><span className="station-label">{experience.number} / {index === 0 ? 'SENSOR SYSTEMS' : index === 1 ? 'CALIBRATION' : 'BUILD'}</span><h3>{experience.company}</h3><p className="station-role">{experience.role} <b>·</b> {experience.duration}</p><p className="body-copy">{experience.description}</p><div className="station-visual" aria-hidden="true">{index === 0 ? <><img className="syscon-waveform-image" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Sep%2030%2C%202026%2C%2011_21_47%20PM-Nc2Ej8cninnCJVS8FCsoB53ZtMXmby.png" alt="Strain gauge sensor waveform" /><b className="measurement-point" /></> : index === 1 ? <><span className="measure-label">SENSING RANGE</span><span className="measure-line" /><b className="measure-point point-one" /><b className="measure-point point-two" /><span className="measure-values">1.00 mm&nbsp;&nbsp; ───────── &nbsp;&nbsp;1.75 mm</span></> : <><span className="task-days">MON&nbsp;&nbsp; TUE&nbsp;&nbsp; WED&nbsp;&nbsp; THU</span><span className="task-readout">09:00&nbsp; TASK<br />12:30&nbsp; MEETING<br />18:00&nbsp; REMINDER</span></>}</div><div className="experience-tags">{experience.tags.filter((tag) => tag !== 'ADC').map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div><div className="experience-close"><span>LEARN</span><i>→</i><span>TEST</span><i>→</i><span>BUILD</span><i>→</i><span>REPEAT</span><small>HARDWARE → SYSTEMS → SOFTWARE</small></div></section>

    

    <section id="research" className="section wrapper research-section"><SectionHead label="05 / RESEARCH">FROM CAMERA TO<br /><span className="heading-accent">SATELLITE.</span></SectionHead><div className="research-grid"><div><span className="eyebrow">IEEE RESEARCH PAPER · ICSSS 2025 · IEEE PUBLISHER</span><h3>Satellite-based Image Transmission with Hazard Detection and Real-Time Environmental Monitoring using LoRa and ESP32-CAM</h3><External>VIEW CERTIFICATE</External></div><div className="research-visual"><div className="earth-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="satellite">ESP32-CAM</span><span className="research-dot">HAZARD</span></div></div><div className="stats"><div><strong>250<small>+</small></strong><span>PROGRAMMING PROBLEMS</span></div><div><strong>03</strong><span>TECHNICAL EXPERIENCES</span></div><div><strong>01</strong><span>IEEE RESEARCH PAPER</span></div><div><strong>08<small>+</small></strong><span>PROJECTS &amp; BUILDS</span></div></div></section>

    <section className="section wrapper current-section" hidden><SectionHead label="06 / CURRENTLY BUILDING">ALWAYS<br />BUILDING SOMETHING.</SectionHead><div className="current-grid">{[['TRAINWAKE','Smart Train Journey Alarm','BUILDING'],['WISHLY','Wishlist & Memory Organizer','EXPLORING'],['VLSI / PHYSICAL DESIGN','Learning & Practice','LEARNING']].map(([title, subtitle, status]) => <article key={title}><span>STATUS: {status}</span><h3>{title}</h3><p>{subtitle}</p><i><b style={{ width: status === 'BUILDING' ? '72%' : status === 'EXPLORING' ? '48%' : '34%' }} /></i></article>)}</div></section>

    <section className="section wrapper education-section"><SectionHead label="07 / EDUCATION">THE FOUNDATION.</SectionHead><div className="education-copy"><span>BACHELOR OF ENGINEERING</span><h3>Electronics and Communication Engineering</h3><p>CMR Institute of Technology</p><strong>CGPA: 8.2 <i>·</i> 2025</strong></div></section>

    <section id="contact" className="contact-section wrapper"><Label>08 / CONTACT</Label><h2>HAVE AN IDEA?<br />LET&apos;S BUILD<br /><em>SOMETHING PRACTICAL.</em></h2><div className="contact-links"><External href="mailto:pragatireddy900@gmail.com"><span>EMAIL<small>pragatireddy900@gmail.com</small></span></External><External href="https://www.linkedin.com"><span>LINKEDIN<small>LinkedIn</small></span></External><External href="https://github.com"><span>GITHUB<small>GitHub</small></span></External></div></section>
    <footer className="site-footer wrapper"><span>Pragathi B.</span><span>ECE · VLSI · SOFTWARE</span><span>© 2026</span></footer><p className="footer-note">BUILT WITH CURIOSITY.</p>
    {trainWakeOpen && <TrainWakeGallery onClose={() => setTrainWakeOpen(false)} />}
    {wishlyOpen && <WishlyGallery onClose={() => setWishlyOpen(false)} />}
    {schedulerOpen && <SchedulerGallery onClose={() => setSchedulerOpen(false)} />}
    {selectedProject && <ZenithCaseStudy projectNumber={selectedProject.number} onClose={() => setSelectedProject(null)} onPrevious={() => setSelectedProject(projects[Math.max(0, projects.findIndex((project) => project.number === selectedProject.number) - 1)])} onNext={() => setSelectedProject(projects[Math.min(projects.length - 1, projects.findIndex((project) => project.number === selectedProject.number) + 1)])} />}
  </main>
}
